import MockTheta.Coordinates

/-!
# Cyclotomic power-basis coordinates

The public `c0` functional is the coordinate of `1` in the power basis
`1, ζ, ..., ζ^(p - 2)`.  The main result of this file proves the general
conversion from `p` redundant coefficients to this genuine power basis:
the constant coordinate is `C 0 - C (p - 1)`.
-/

noncomputable section

open scoped BigOperators

namespace MockTheta

open Finset Polynomial

universe u v

variable {p : ℕ} {K : Type u} {L : Type v}
variable [NeZero p] [Field K] [Field L] [Algebra K L]
variable [IsCyclotomicExtension {p} K L]

/-- Constant coordinate in the power basis generated by a primitive root. -/
noncomputable def c0 {ζ : L} (hζ : IsPrimitiveRoot ζ p) : L →ₗ[K] K where
  toFun x :=
    (hζ.powerBasis K).basis.repr x
      ⟨0, (hζ.powerBasis K).dim_pos⟩
  map_add' x y := by simp
  map_smul' a x := by simp

variable {ζ : L} (hζ : IsPrimitiveRoot ζ p)

private theorem powerBasis_dim_prime (hp : p.Prime)
    (hirr : Irreducible (cyclotomic p K)) :
    (hζ.powerBasis K).dim = p - 1 := by
  letI : NeZero (p : K) := IsCyclotomicExtension.neZero' p K L
  rw [hζ.powerBasis_dim K,
    ← hζ.minpoly_eq_cyclotomic_of_irreducible hirr,
    natDegree_cyclotomic, Nat.totient_prime hp]

theorem c0_pow_of_lt (hp : p.Prime)
    (hirr : Irreducible (cyclotomic p K)) {n : ℕ} (hn : n < p - 1) :
    c0 (K := K) hζ (ζ ^ n) = if n = 0 then 1 else 0 := by
  let pb := hζ.powerBasis K
  have hdim : pb.dim = p - 1 := powerBasis_dim_prime hζ hp hirr
  let i : Fin pb.dim := ⟨n, by simpa [hdim] using hn⟩
  have hpow : ζ ^ n = pb.basis i := by
    rw [pb.basis_eq_pow]
    simp only [i]
    rw [hζ.powerBasis_gen K]
  rw [hpow]
  unfold c0
  simp only [LinearMap.coe_mk, AddHom.coe_mk]
  rw [Module.Basis.repr_self_apply]
  congr 1
  simp only [i]
  apply propext
  constructor
  · intro h
    exact congrArg Fin.val h
  · intro h
    apply Fin.ext
    simpa using h

theorem c0_one (hp : p.Prime) (hirr : Irreducible (cyclotomic p K)) :
    c0 (K := K) hζ 1 = 1 := by
  rw [← pow_zero ζ,
    c0_pow_of_lt hζ hp hirr (Nat.sub_pos_of_lt hp.one_lt)]
  simp

theorem c0_pow_ne_zero (hp : p.Prime)
    (hirr : Irreducible (cyclotomic p K)) {n : ℕ}
    (hn : n < p - 1) (hn0 : n ≠ 0) :
    c0 (K := K) hζ (ζ ^ n) = 0 := by
  rw [c0_pow_of_lt hζ hp hirr hn, if_neg hn0]

theorem c0_pow_pred (hp : p.Prime)
    (hirr : Irreducible (cyclotomic p K)) :
    c0 (K := K) hζ (ζ ^ (p - 1)) = -1 := by
  have hpow := hζ.pow_sub_one_eq hp.one_lt
  rw [Nat.pred_eq_sub_one] at hpow
  rw [hpow, map_neg, map_sum]
  have hsum :
      ∑ i ∈ range (p - 1), c0 (K := K) hζ (ζ ^ i) =
        (1 : K) := by
    have hmem : 0 ∈ range (p - 1) := by
      simpa using hp.one_lt
    rw [sum_eq_add_sum_sdiff_singleton_of_mem hmem]
    · rw [pow_zero, c0_one hζ hp hirr]
      have hz :
          ∑ i ∈ (Finset.range (p - 1)) \ ({0} : Finset ℕ),
            c0 (K := K) hζ (ζ ^ i) = 0 := by
        apply sum_eq_zero
        intro i hi
        have hi' :
            i ∈ Finset.range (p - 1) ∧ i ∉ ({0} : Finset ℕ) :=
          Finset.mem_sdiff.mp hi
        rw [c0_pow_ne_zero hζ hp hirr]
        · exact Finset.mem_range.mp hi'.1
        · intro hzero
          subst i
          exact hi'.2 (by simp)
      rw [hz, add_zero]
  rw [hsum]

/-- Conversion from a redundant length-`p` coefficient vector to the genuine
constant coordinate in the length-`p-1` cyclotomic power basis. -/
theorem c0_redundant_sum (hp : p.Prime)
    (hirr : Irreducible (cyclotomic p K)) (C : ℕ → K) :
    c0 (K := K) hζ
        (∑ m ∈ range p, algebraMap K L (C m) * ζ ^ m) =
      C 0 - C (p - 1) := by
  have hdecomp :
      (∑ m ∈ range p, algebraMap K L (C m) * ζ ^ m) =
        (∑ m ∈ range (p - 1),
          algebraMap K L (C m) * ζ ^ m) +
          algebraMap K L (C (p - 1)) * ζ ^ (p - 1) := by
    calc
      _ = ∑ m ∈ range ((p - 1) + 1),
          algebraMap K L (C m) * ζ ^ m := by
            rw [Nat.sub_add_cancel
              (Nat.one_le_iff_ne_zero.mpr hp.ne_zero)]
      _ = _ := by rw [sum_range_succ]
  rw [hdecomp, map_add, map_sum]
  have hmain :
      ∑ x ∈ range (p - 1), c0 (K := K) hζ
        (algebraMap K L (C x) * ζ ^ x) = C 0 := by
    have hmem : 0 ∈ range (p - 1) := by
      simpa using hp.one_lt
    rw [sum_eq_add_sum_sdiff_singleton_of_mem hmem]
    · rw [← Algebra.smul_def, map_smul, pow_zero,
        c0_one hζ hp hirr, smul_eq_mul, mul_one]
      have hz :
          ∑ x ∈ (Finset.range (p - 1)) \ ({0} : Finset ℕ),
            c0 (K := K) hζ
              (algebraMap K L (C x) * ζ ^ x) = 0 := by
        apply sum_eq_zero
        intro i hi
        have hi' :
            i ∈ Finset.range (p - 1) ∧ i ∉ ({0} : Finset ℕ) :=
          Finset.mem_sdiff.mp hi
        rw [← Algebra.smul_def, map_smul,
          c0_pow_ne_zero hζ hp hirr
            (Finset.mem_range.mp hi'.1) (by simpa using hi'.2),
          smul_zero]
      rw [hz, add_zero]
  rw [hmain, ← Algebra.smul_def, map_smul,
    c0_pow_pred hζ hp hirr, smul_eq_mul]
  ring

end MockTheta
